### ISSUE TITLE
Bug when stopping scheduler with jobs running - APScheduler v4

### ISSUE THREAD

**Issue by mattewid** [agronholm/apscheduler#946]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

4.0.0a5

### What happened?

**Hello,**

I would like to report a bug that occurs after stopping the Scheduler. From what I have noticed, the bug occurs when I stop the scheduler while there is a job running.

Summary: While a job is still running, I use the scheduler's .stop method. I wait until the scheduler.state is in the stopped state. I see that when it reaches the scheduler.state.stopped state, the job that was running before I stopped the scheduler is completed successfully. However, some operations remain pending in the DataStore, such as decreasing the running_jobs of the task document, and the job is not deleted from the job collection.

Tested only with *MongoDBDataStore*

### How can we reproduce the bug?

**Code to replicate the bug:**
```py
from apscheduler import (
    Scheduler,
    SchedulerRole,
    TaskDefaults,
    RunState
)
from apscheduler.datastores.mongodb import (
    MongoDBDataStore
)
from apscheduler.triggers.interval import IntervalTrigger

from apscheduler.executors.thread import ThreadPoolJobExecutor
from datetime import datetime
import time

import logging

logging.basicConfig()
logging.getLogger('apscheduler').setLevel(logging.INFO)



MONGO_DB_URI = '<your-mongodb-uri>'
DB_NAME_FOR_APS = 'tryreplybugaps'


scheduler_web_configs = dict(
    data_store=MongoDBDataStore(
        client_or_uri=MONGO_DB_URI,
        database=DB_NAME_FOR_APS
    ),
    role=SchedulerRole.both,
    max_concurrent_jobs=100,
    job_executors={
        'threadpool': ThreadPoolJobExecutor()
    },
    task_defaults=TaskDefaults(
        job_executor='threadpool',
        max_running_jobs=1
    )
)

with Scheduler(
    **scheduler_web_configs
    ) as scheduler:
    

    def my_job_func() -> None:

        print('In a lengthy process...')
        time.sleep(10)
        print('Long process completed.')

        return None


    scheduler.add_schedule(
        my_job_func, # This will run in `threadpool` as specified in TaskDefaults.
        trigger=IntervalTrigger(
            hours=1,
            start_time=datetime.now()
        )
    )

    scheduler.start_in_background()


    while len(scheduler._async_scheduler._running_jobs) == 0:
        print('Waiting for some job to start running...')
        time.sleep(5)
    

    print('Stopping the scheduler when there are still jobs running...', scheduler._async_scheduler._running_jobs)
    scheduler.stop()


    while scheduler.state != RunState.stopped:
        print('Waiting for the scheduler to be in the stopped state...')
        time.sleep(2)


    assert len(scheduler._async_scheduler._running_jobs) == 0


    datastore_tasks = scheduler.get_tasks() # The task continues with the field running_jobs=1
    datastore_jobs = scheduler.get_jobs() # The job was not deleted after execution.

    print('Tasks:', datastore_tasks)
    print('Jobs:', datastore_jobs)

    """
    In my case, the execution went well. The job was completed.

    However, in the task document in the database, the task continues with the field running_jobs=1.,
    But the job is no longer being executed, and this will prevent a new start of the schedule tasks in the next program starts,
    since I use max_running_jobs=1.

    And in the jobs collection, the job document remains in the database. Which I believe should have been deleted, right?
    """
```

**My logs running the sample code:**
```
INFO:apscheduler._schedulers.async_:Added new schedule (task='__main__:my_job_func', trigger=IntervalTrigger(hours=1, start_time='2024-07-28 18:58:32.458838-03:00')); next run time at 2024-07-28 18:58:32.458838-03:00
INFO:apscheduler._schedulers.async_:Scheduler started
Waiting for some job to start running...
In a lengthy process...
Stopping the scheduler when there are still jobs running... {Job(id=UUID('1503845e-75bf-4c90-a583-b0bc138a94ce'), task_id='__main__:my_job_func', schedule_id='a3325d5d-1ff6-4ff4-8ca8-e8ad934ac782', scheduled_fire_time=datetime.datetime(2024, 7, 28, 18, 58, 32, 458838, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=75600))), executor='threadpool', created_at=datetime.datetime(2024, 7, 28, 21, 58, 33, 230771, tzinfo=datetime.timezone.utc))}
Waiting for the scheduler to be in the stopped state...
Waiting for the scheduler to be in the stopped state...
Waiting for the scheduler to be in the stopped state...
Waiting for the scheduler to be in the stopped state...
Long process completed.
INFO:apscheduler._schedulers.async_:Job 1503845e-75bf-4c90-a583-b0bc138a94ce completed successfully
INFO:apscheduler._schedulers.async_:Scheduler stopped
Tasks: [
    Task(
        id='__main__:my_job_func',
        func='__main__:my_job_func',
        job_executor='threadpool',
        max_running_jobs=1,
        misfire_grace_time=None,
        running_jobs=1
        )
    ]
Jobs: [
    Job(
        id=UUID('1503845e-75bf-4c90-a583-b0bc138a94ce'),
        task_id='__main__:my_job_func',
        schedule_id='a3325d5d-1ff6-4ff4-8ca8-e8ad934ac782',
        scheduled_fire_time=datetime.datetime(2024, 7, 28, 18, 58, 32, 458838,
        tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=75600))),
        executor='threadpool',
        created_at=datetime.datetime(2024, 7, 28, 21, 58, 33, 230771, tzinfo=datetime.timezone.utc)
    )
    ]
```

**Comment by agronholm** [comment]
I see two problems in the code:

1. The `stop()` method is a bit too forceful (by default), and should probably not cancel the scheduler's task group
2. The job acquisition operation isn't exactly atomic on MongoDB (I don't know how to actually accomplish that given its nature), but a cancellation will abort the operation halfway through.

**Comment by HK-Mattew** [comment]
> 1. The `stop()` method is a bit too forceful (by default), and should probably not cancel the scheduler's task group

However, the expected behavior when the job is completed normally is:

- Acquire job
- Execute job
- Delete job
- In the task, decrement the running_jobs field

However, in my case, I used Scheduler.stop before the job was completed. Then the Scheduler showed me the log *Job ...id... completed successfully*, so the job was completed. However, the job was not deleted from the datastore and the task did not have its running_jobs decrement.

My question is, what is causing the scheduler not to delete the job at the end of its execution and also why did it not decrement the task's running_jobs field?


> 2\. The job acquisition operation isn't exactly atomic on MongoDB (I don't know how to actually accomplish that given its nature), but a cancellation will abort the operation halfway through.

In pymongo you can use Transactions within a session. But I don't think it's necessary in this case, because the task was not canceled or got an error. The job was completed successfully.

If I'm leaving anything unnoticed please let me know.

**Comment by agronholm** [comment]
> In pymongo you can use Transactions within a session. But I don't think it's necessary in this case, because the task was not canceled or got an error. The job was completed successfully.

Transactions don't work on a single node Mongo server.

**Comment by agronholm** [comment]
> My question is, what is causing the scheduler not to delete the job at the end of its execution and also why did it not decrement the task's running_jobs field?

Because `stop()` currently cancels all the task groups within the scheduler, and there is no shielding to prevent the job release operation from being cancelled.

**Comment by HK-Mattew** [comment]
> > My question is, what is causing the scheduler not to delete the job at the end of its execution and also why did it not decrement the task's running_jobs field?
> 
> Because `stop()` currently cancels all the task groups within the scheduler, and there is no shielding to prevent the job release operation from being cancelled.

I understood

**Comment by agronholm** [comment]
> > > In pymongo you can use Transactions within a session. But I don't think it's necessary in this case, because the task was not canceled or got an error. The job was completed successfully.
> > 
> > 
> > Transactions don't work on a single node Mongo server.
> 
> You are right. So that would be the difficulty because not everyone uses MongoDB with more than one node :/
> 
> I use MongoDB with more than one node. So I think I would have to try to adapt something like MongoDBDataStore(allow_transaction=True)

How would that help users with just one node?

**Comment by HK-Mattew** [comment]
> allow_transaction

Unfortunately this would still be a problem. Since transactions would only work for those who used allow_transaction=True

**Comment by HK-Mattew** [comment]
I found a temporary solution to the problem I'm facing. Just save the jobs that were running when the scheduler stopped and use the .release_job method manually, like this:

```py
asyncio.run(
       scheduler.data_store.release_job(
           ...
           )
)
```

This worked correctly even after the scheduler stopped.

**Comment by agronholm** [comment]
> I found a temporary solution to the problem I'm facing. Just save the jobs that were running when the scheduler stopped and use the .release_job method manually, like this:
> 
> ```python
> asyncio.run(
>        scheduler.data_store.release_job(
>            ...
>            )
> )
> ```
> 
> This worked correctly even after the scheduler stopped.

This is a dangerous looking "fix". You should be aware that I'm currently in the process of refactoring the `stop()` method to allow the scheduler to shut down more gracefully, allowing jobs to complete properly if they do so within the allotted time. I'm also considering shielding the release operations from `CancelScope` cancellation if possible.

**Comment by HK-Mattew** [comment]
> This is a dangerous looking "fix". You should be aware that I'm currently in the process of refactoring the `stop()` method to allow the scheduler to shut down more gracefully, allowing jobs to complete properly if they do so within the allotted time. I'm also considering shielding the release operations from `CancelScope` cancellation if that looks like it makes sense.

It's not really the best solution. But it would help temporarily.

Your idea about CancelScope sounds good. I hope it works well :)

[Another idea]
One idea I had would be to work with signals in the Scheduler.

Example:
```py
class Scheduler():
      ...

scheduler = Scheduler()

scheduler.send_signal('stop running new jobs')

"""
I wait until no jobs are running in the scheduler and then use the scheduler.stop() method.
With this, the scheduler would be able to process the job deletion operations after they are executed,
and also decrement the task running_jobs field.
"""

assert len(scheduler._async_scheduler._running_jobs) == 0

scheduler.stop()
```

This seems like a good solution to the current problem.

**Comment by agronholm** [comment]
The `stop()` method already sets the scheduler state to `stopping` which signals to the background tasks that they should exit their respective loops. Unfortunately, currently there are background tasks which sleep for certain periods of time, and I have to find a way to safely interrupt these tasks in order to allow their task groups to exit.

**Comment by HK-Mattew** [comment]
> The `stop()` method already sets the scheduler state to `stopping` which signals to the background tasks that they should exit their respective loops. Unfortunately, currently there are background tasks which sleep for certain periods of time, and I have to find a way to safely interrupt these tasks in order to allow their task groups to exit.

I just checked and, indeed, the AsyncScheduler._process_jobs method has a condition to only run with RunState.started.

So, I think the best bet would be your idea about CancelScope.

Man, I'd like to take this opportunity to thank you for your great work. This new version of APScheduler is looking amazing. I really like it. 😉

**Comment by agronholm** [comment]
> So, I think the best bet would be your idea about CancelScope.

I'm not sure we're on the same page here. I brought up `CancelScope` because those could be used to shield certain sensitive operations (like releasing a job) from cancellation.

> Man, I'd like to take this opportunity to thank you for your great work. This new version of APScheduler is looking amazing. I really like it. 😉

Thanks! Always nice to see one's work appreciated!

**Comment by neeraj9** [comment]
I noticed that with postgresql datastore if scheduler is terminated abruptly due to a program crashing or terminating then the running_jobs is left as is. There should be a reconciliation logic when the scheduler starts to align jobs (in `jobs` table) with running_jobs in the `tasks` table.

I am using async job_executor and having max_running_jobs greater than 1 to allow many jobs per task.

**Comment by agronholm** [comment]
Yeah, that was the intention. Things like this is the reason it's still in alpha.

**Comment by agronholm** [comment]
I think this problem is now fixed in `master`.

**Comment by mattewid** [comment]
I just ran the code reproduced above on the master branch. And I found that the problem still persists.

**First run logs:**
```
INFO:apscheduler._schedulers.async_:Added new schedule (task='__main__:my_job_func', trigger=IntervalTrigger(hours=1, start_time='2025-04-27 08:01:07.919292-03:00')); next run time at 2025-04-27 08:01:07.919292-03:00
INFO:apscheduler._schedulers.async_:Scheduler started
Waiting for some job to start running...
In a lengthy process...
Stopping the scheduler when there are still jobs running... {Job(id=UUID('3aef8fb7-51c0-46fe-ac63-057a6abbe828'), task_id='__main__:my_job_func', schedule_id='05a937ce-6a4d-4903-ba16-a37d45cc988f', scheduled_fire_time=datetime.datetime(2025, 4, 27, 8, 1, 7, 919292, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=75600))), executor='threadpool', metadata={}, created_at=datetime.datetime(2025, 4, 27, 11, 1, 8, 899509, tzinfo=datetime.timezone.utc))}
Waiting for the scheduler to be in the stopped state...
Waiting for the scheduler to be in the stopped state...
Waiting for the scheduler to be in the stopped state...
Waiting for the scheduler to be in the stopped state...
Long process completed.
INFO:apscheduler._schedulers.async_:Job 3aef8fb7-51c0-46fe-ac63-057a6abbe828 completed successfully
INFO:apscheduler._schedulers.async_:Scheduler stopped
Tasks: [
Task(
    id='__main__:my_job_func',
    func='__main__:my_job_func',
    job_executor='threadpool',
    max_running_jobs=1,
    misfire_grace_time=None,
    metadata={},
    running_jobs=1)
]
Jobs: [
    Job(id=UUID('3aef8fb7-51c0-46fe-ac63-057a6abbe828'),
    task_id='__main__:my_job_func',
    schedule_id='05a937ce-6a4d-4903-ba16-a37d45cc988f',
    scheduled_fire_time=datetime.datetime(2025, 4, 27, 8, 1, 7, 919292,
    tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=75600))),
    executor='threadpool', metadata={},
    created_at=datetime.datetime(2025, 4, 27, 11, 1, 8, 899509,
    tzinfo=datetime.timezone.utc))
]
```
Note that even though the job has completed successfully, the task continues with running_jobs=1 and the job is not deleted.

**Second run logs:**
```
INFO:apscheduler._schedulers.async_:Added new schedule (task='__main__:my_job_func', trigger=IntervalTrigger(hours=1, start_time='2025-04-27 08:04:26.090288-03:00')); next run time at 2025-04-27 08:04:26.090288-03:00
INFO:apscheduler._schedulers.async_:Scheduler started
Waiting for some job to start running...
Waiting for some job to start running...
Waiting for some job to start running...
Waiting for some job to start running...
Waiting for some job to start running...
Waiting for some job to start running...
Waiting for some job to start running...
Waiting for some job to start running...
Waiting for some job to start running...
Waiting for some job to start running...
Waiting for some job to start running...
Waiting for some job to start running...
Waiting for some job to start running...
Waiting for some job to start running...
```
Note that now a new job will never be executed again. Since the task has running_jobs=1 and max_running_jobs=1

**Comment by agronholm** [comment]
Bummer. I'm not sure _why_ this happens, as the scheduler should gracefully stop any running jobs and then release them. I'll investigate.

> Note that now a new job will never be executed again. Since the task has running_jobs=1 and max_running_jobs=1

The job should expire at some point, allowing the scheduler to run a new one once the old one has been cleaned up. In v4.0.0a6 this would be even faster with a fixed scheduler ID.

**Comment by agronholm** [comment]
Huh...I can't reproduce this with PostgreSQL.

**Comment by mattewid** [comment]
> Huh...I can't reproduce this with PostgreSQL.

Maybe it's the way you're reproducing. Did you use scheduler.stop()?

**Comment by agronholm** [comment]
All I did was switch out the data store.

**Comment by mattewid** [comment]
I was doing some tests on the code, and I realized that the problem is related to the use of the to_thread.run_sync method https://github.com/agronholm/apscheduler/blob/b2f2a3c6b01da31552974399c4a8614cbcf5b3b4/src/apscheduler/datastores/mongodb.py#L791 The operation passed to to_thread.run_sync is not being executed. (At least not after using scheduler.stop)

And why is this not happening with PostgreSQL? Possibly because SQLAlchemy datastore is not using to_thread.run_sync in some cases: https://github.com/agronholm/apscheduler/blob/b2f2a3c6b01da31552974399c4a8614cbcf5b3b4/src/apscheduler/datastores/sqlalchemy.py#L264

**Comment by mattewid** [comment]
> Not being executed? You mean it's being cancelled...?

Actually, I'm not sure. It seems that to_thread.run_sync does nothing (it doesn't generate an error or anything).

I tested it by removing to_thread.run_sync and running the update directly on the pymongo collection and it worked perfectly. (Of course this blocks the event loop, I'm not considering this as a solution).

**Comment by agronholm** [comment]
> > Not being executed? You mean it's being cancelled...?
> 
> Actually, I'm not sure. It seems that to_thread.run_sync does nothing (it doesn't generate an error or anything).
> 
> I tested it by removing to_thread.run_sync and running the update directly on the pymongo collection and it worked perfectly. (Of course this blocks the event loop, I'm not considering this as a solution).

Perhaps it's a race condition of some kind then? It would make no sense that `to_thread.run_sync()` didn't do anything (a lot of code out there relies on that!)

**Comment by mattewid** [comment]
See what I did on the line: https://github.com/agronholm/apscheduler/blob/b2f2a3c6b01da31552974399c4a8614cbcf5b3b4/src/apscheduler/datastores/mongodb.py#L791

```py
# Delete the job 
print('before delete') 
await to_thread.run_sync( 
lambda: self._jobs.delete_one({"_id": result.job_id}, session=session) 
) 
print('after delete')
```
**print('after delete')** is not executed using to_thread.run_sync. I don't know why

**Comment by mattewid** [comment]
It looks like a blockage

**Comment by agronholm** [comment]
Sounds more like the task is being cancelled. That would explain why `after delete` isn't printed.

**Comment by mattewid** [comment]
Do you mean the ._release_job task? Because when I use: self._jobs.delete_one({"_id": result.job_id}, session=session) directly without using to_thread.run_sync it works.

**Comment by agronholm** [comment]
Yes, because there is no yield point so cancellation can't take effect.

**Comment by mattewid** [comment]
Now I get it. Not using to_thread.run_sync causes cancellation to block

**Comment by agronholm** [comment]
I'll dig deeper into this later. I'm sure I'll be able to figure out the root cause at least.

**Comment by agronholm** [comment]
See if this fixes it for you:
```diff
diff --git a/src/apscheduler/_schedulers/async_.py b/src/apscheduler/_schedulers/async_.py
--- a/src/apscheduler/_schedulers/async_.py	(revision b2f2a3c6b01da31552974399c4a8614cbcf5b3b4)
+++ b/src/apscheduler/_schedulers/async_.py	(date 1745790934276)
@@ -1201,10 +1201,10 @@
                 retval = await job_executor.run_job(func, job)
             except get_cancelled_exc_class():
                 self.logger.info("Job %s was cancelled", job.id)
-                with CancelScope(shield=True):
-                    result = JobResult.from_job(
-                        job, JobOutcome.cancelled, started_at=start_time
-                    )
+                result = JobResult.from_job(
+                    job, JobOutcome.cancelled, started_at=start_time
+                )
+                with CancelScope(shield=True):
                     await self.data_store.release_job(self.identity, job, result)
             except BaseException as exc:
                 if isinstance(exc, Exception):
@@ -1220,9 +1220,10 @@
                     started_at=start_time,
                     exception=exc,
                 )
-                await self.data_store.release_job(self.identity, job, result)
-                if not isinstance(exc, Exception):
-                    raise
+                with CancelScope(shield=True):
+                    await self.data_store.release_job(self.identity, job, result)
+                    if not isinstance(exc, Exception):
+                        raise
             else:
                 self.logger.info("Job %s completed successfully", job.id)
                 result = JobResult.from_job(
@@ -1231,7 +1232,8 @@
                     started_at=start_time,
                     return_value=retval,
                 )
-                await self.data_store.release_job(self.identity, job, result)
+                with CancelScope(shield=True):
+                    await self.data_store.release_job(self.identity, job, result)
             finally:
                 current_job.reset(token)
         finally:
```

**Comment by mattewid** [comment]
@agronholm It worked perfectly

**Comment by mattewid** [comment]
> See if this fixes it for you:

Hi,

Is this the solution to this problem? If so, are you working on it to submit to the master branch?

**Comment by agronholm** [comment]
Yeah, just yesterday I was just working on a test so I could incorporate this patch to master. However, for some reason my test was passing even without the patch so I'm still investigating why that happened.

**Comment by mattewid** [comment]
> Yeah, just yesterday I was just working on a test so I could incorporate this patch to master. However, for some reason my test was passing even without the patch so I'm still investigating why that happened.

That's fine. If you need me to test something, just let me know.
